#!/bin/sh
# ─────────────────────────────────────────────────────────────────────────────
# setup_local.sh  —  WiFiRadarX one-time local setup for Termux / Linux
#
# Run this ONCE after cloning the repo, before your first local build.
# It downloads the gradle-wrapper.jar binary (not committed to git) and
# checks that the Java toolchain is present.
#
# Usage:
#   chmod +x setup_local.sh
#   ./setup_local.sh
# ─────────────────────────────────────────────────────────────────────────────
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
JAR="$SCRIPT_DIR/gradle/wrapper/gradle-wrapper.jar"

echo ""
echo "  WiFiRadarX — Local Build Setup"
echo "  ================================"
echo ""

# ── 1. gradle-wrapper.jar ────────────────────────────────────────────────────
if [ -f "$JAR" ] && [ "$(wc -c < "$JAR")" -gt 10000 ]; then
    echo "  ✅ gradle-wrapper.jar already present ($(du -sh "$JAR" | cut -f1))"
else
    echo "  ⬇  Downloading gradle-wrapper.jar …"
    mkdir -p "$SCRIPT_DIR/gradle/wrapper"

    # Attempt 1: raw.githubusercontent.com
    if curl -fsSL --retry 3 --max-time 60 \
        "https://raw.githubusercontent.com/gradle/gradle/v8.7.0/gradle/wrapper/gradle-wrapper.jar" \
        -o "$JAR" 2>/dev/null && [ "$(wc -c < "$JAR")" -gt 10000 ]; then
        echo "  ✅ Downloaded from GitHub raw"

    # Attempt 2: services.gradle.org distribution zip
    elif curl -fsSL --retry 2 --max-time 120 \
        "https://services.gradle.org/distributions/gradle-8.7-bin.zip" \
        -o /tmp/_gradle_dist.zip 2>/dev/null; then
        echo "  📦 Extracting from Gradle distribution…"
        unzip -p /tmp/_gradle_dist.zip "gradle-8.7/lib/plugins/gradle-wrapper-8.7.jar" \
            > "$JAR" 2>/dev/null || \
        unzip -jo /tmp/_gradle_dist.zip "*/gradle-wrapper.jar" -d "$(dirname "$JAR")" 2>/dev/null
        rm -f /tmp/_gradle_dist.zip
        echo "  ✅ Extracted from distribution"

    # Fallback: Termux native gradle
    elif command -v gradle >/dev/null 2>&1; then
        echo "  🔧 Using local Gradle to regenerate wrapper…"
        cd "$SCRIPT_DIR"
        gradle wrapper --gradle-version 8.7 --distribution-type bin
        echo "  ✅ Wrapper generated by local Gradle"

    else
        echo ""
        echo "  ❌ Could not obtain gradle-wrapper.jar automatically."
        echo ""
        echo "  Fix options:"
        echo "    Option A (Termux): pkg install gradle && gradle wrapper"
        echo "    Option B:          Copy gradle-wrapper.jar from Android Studio:"
        echo "                       ~/.gradle/wrapper/dists/gradle-8.7-bin/*/gradle-8.7/lib/plugins/gradle-wrapper-8.7.jar"
        echo ""
        exit 1
    fi
fi

# ── 2. gradlew permissions ───────────────────────────────────────────────────
chmod +x "$SCRIPT_DIR/gradlew"
echo "  ✅ gradlew is executable"

# ── 3. Java check ────────────────────────────────────────────────────────────
if command -v java >/dev/null 2>&1; then
    JAVA_VER=$(java -version 2>&1 | head -1)
    echo "  ✅ Java found: $JAVA_VER"
else
    echo "  ⚠  Java not found."
    echo "     In Termux: pkg install openjdk-17"
    echo "     On Linux:  sudo apt install openjdk-17-jdk"
fi

# ── 4. Android SDK check ─────────────────────────────────────────────────────
if [ -n "$ANDROID_HOME" ] && [ -d "$ANDROID_HOME" ]; then
    echo "  ✅ ANDROID_HOME = $ANDROID_HOME"
else
    echo "  ⚠  ANDROID_HOME not set."
    echo "     In Termux: Install Android SDK via:"
    echo "       pkg install aapt apksigner dx"
    echo "     Or set ANDROID_HOME to your SDK path in ~/.bashrc"
fi

echo ""
echo "  ─────────────────────────────────────────────"
echo "  Setup complete!  Build commands:"
echo ""
echo "    Debug APK (fast, no minify):"
echo "      cd $SCRIPT_DIR"
echo "      ./gradlew assembleDebug"
echo "      # APK → app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "    Release APK (minified):"
echo "      ./gradlew assembleRelease"
echo "      # APK → app/build/outputs/apk/release/app-release-unsigned.apk"
echo "  ─────────────────────────────────────────────"
echo ""
