-keep class com.wifiradarx.app.data.entity.** { *; }
-keep class com.wifiradarx.app.intelligence.** { *; }
-keepattributes *Annotation*
-keepclassmembers class * extends androidx.room.RoomDatabase { *; }
-keep class * extends androidx.room.RoomDatabase
-dontwarn com.google.ar.**
-keep class com.google.ar.** { *; }
-keep class com.github.mikephil.** { *; }
-dontwarn com.github.mikephil.**
